### ISSUE TITLE
Devcontainer gets stuck during installation of python packages

### ISSUE THREAD

**Issue by Salazander** [ai-workshop-ise/ai-hands-on-lab#2]
When installing all requirements specified in ./devcontainer/requirements.txt, my dev laptop gets stuck during installation.
The same happens during startup of the devcontainer (on my dev laptop).
Installing the packages in smaller chunks seems to circumvent the issue but takes ages to complete.
```
"postCreateCommand": "virtualenv -p3.9 .myvenv && . .myvenv/bin/activate && for line in $(cat .devcontainer/requirements.txt); do pip3 install $(echo $line); done"
```

**Comment by adinastoll** [comment]
Hi @Salazander, thanks for raising this issue and apologies for the inconvenience.  

We have one particular dependency (sentence-transformers) which pulls two other big packages (pytorch and cudnn) which turned out to be incredibly slow on some machines. We noticed that removing the virtual env from the devcontainer and installing all dependencies directly in the container led to a faster installation.

However, we have decided to remove the devcontainer option at the moment. 

The recommended way to set things up is by creating a virtual environment in VSCode - which worked reasonably fast on all machines we have tried. 

See below the [steps](https://github.com/ai-workshop-ise/ai-hands-on-lab/blob/main/book/1.setup.ipynb), and let us know if you encounter any issues. Thank you! 

![image](https://github.com/ai-workshop-ise/ai-hands-on-lab/assets/6609080/57d4e55f-57b6-4e00-a069-05c0a6338e4b)
